<!-- ###############################################
Programmer: Walter VanderHeide
Contact:	wvander@iimage.com
Release Version
History: 						1.0 -- May 1, 2001
								2.0 -- May 10, 2001
								3.0 -- May 15, 2001

Summary of Modifications: 
May 10,2001 -- 	Changed "removing items" so that just the first 
						 	day of an event has an associated check box.
						-- Added the abilitiy to update data.		
						
May 15, 2001 -- Added "time" to admin form
						-- Display data sorted by time
						-- Added a "day view" page...accessed by 
							clicking day on main calendar.
						-- Improved the look of details.asp
#################################################### -->